### ISSUE TITLE
Jenkins can't find sitespeed.io module

### ISSUE THREAD

**Issue by coderDem** [sitespeedio/jenkins.sitespeed.io#18]
Hello,

I set the full path to local sitespeed.io installation

![path](https://cloud.githubusercontent.com/assets/2386100/6960637/cbd906ac-d924-11e4-9c0e-6e16ba02bb83.PNG)

But he can't find the module. So I get this error:
<code>
Couldn't store the file /srv/ci/workspace/Sitespeed.io_XXXXX/budget.jsonjava.io.FileNotFoundException: /srv/ci/workspace/Sitespeed.io_XXXXX/budget.json (No such file or directory)
Couldn't close the writer for /srv/ci/workspace/Sitespeed.io_XXXXX/budget.jsonjava.lang.NullPointerException
Will run executable'/srv/ci/workspace/Sitespeed.io_XXXXX/node_modules/sitespeed.io/bin/' with arguments: ['/srv/ci/workspace/Sitespeed.io_XXXXX/node_modules/sitespeed.io/bin/', -r, /srv/ci/workspace/Sitespeed.io_XXXXX/18/sitespeed-result, --junit, -u, https://novosales-egypt-ishop.novomind.com/, --budget, /srv/ci/workspace/Sitespeed.io_XXXXX/budget.json, -d, 0]
java.io.IOException: Cannot run program "'/srv/ci/workspace/Sitespeed.io_XXXXX/node_modules/sitespeed.io/bin/'": error=2, No such file or directory</code>

What can I do to provide the right path to the sitespeed.io ?

**Comment by soulgalore** [comment]
Hi @coderDem ,
you could skip adding the full path (that is more for if you have built your own version) and then make sure the user running Jenkins have the module in the paths something like this:
<code>export PATH="/usr/local/bin:$PATH"</code> or set it up Global properties in the *Configure system* part in Jenkins.

Best
Peter

**Comment by coderDem** [comment]
Ok I set an entry in Global properties.
Are you mean like this:
![global_properties](https://cloud.githubusercontent.com/assets/2386100/6961214/6ce26026-d929-11e4-9e14-75c9aca95d63.PNG)

**Comment by soulgalore** [comment]
Hi @coderDem ,
sorry didn't have Jenkins setup before. Ok so easiest I think is what you did in the first but you need to point out the exact file, so if you installed it globally it should be something like <code>/usr/local/bin/sitespeed.io</code>  or else point out the js file something like <code>...lib/node_modules/sitespeed.io/bin/sitespeed.js</code>

Sorry again that I was unclear in my first answer.
Best
Peter

**Comment by coderDem** [comment]
Hi @soulgalore,

no problem. Thank you for the tip. It works with pointing to .../bin/sitespeed.js.

Best 
coderDem

**Comment by softwareklinic** [comment]
While running mvn package - i'm receiving 

Sep 14, 2015 9:35:18 AM hudson.TcpSlaveAgentListener <init>
INFO: JNLP slave agent listener started on TCP port 49762
Sep 14, 2015 9:35:18 AM hudson.UDPBroadcastThread run
WARNING: UDP handling problem
java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179)
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
	at hudson.UDPBroadcastThread.run(UDPBroadcastThread.java:76)

Sep 14, 2015 9:35:18 AM org.mortbay.log.Slf4jLog info
INFO: jetty-6.1.26
Sep 14, 2015 9:35:18 AM org.mortbay.log.Slf4jLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Sep 14, 2015 9:35:18 AM org.mortbay.log.Slf4jLog info
INFO: Started SocketConnector@0.0.0.0:49763
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 7.145 sec <<< FAILURE!

Results :

Tests in error: 
  org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite(org.jvnet.hudson.test.junit.FailedTest): -1
  testCliSanity(org.jvnet.hudson.test.PluginAutomaticTestBuilder$CliSanityTest): second instance

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
