### ISSUE TITLE
sitespeed plugin build issue in Jenkins

### ISSUE THREAD

**Issue by BKarthikeyan** [sitespeedio/jenkins.sitespeed.io#24]
I am getting following issue on adding sitespeed plugin in Jenkins. Help me to fix the issue.Thanks!
**Build step failed with exception**
java.lang.IllegalArgumentException: D:\*****\Downloads\JENKINS_HOME\workspace\sitespeedtest\7\sitespeed-result is not a directory
	at io.sitespeed.jenkins.util.FileUtil.getLastModifiedFileNameInDir(FileUtil.java:77)
	at io.sitespeed.jenkins.SitespeedBuilder.perform(SitespeedBuilder.java:244)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by soulgalore** [comment]
Hey @BKarthikeyan 
try run it standalone in the bash field in jenkins, you will have more flexibility + will be easier to upgrade to 4.0.

Best
Peter

**Comment by BKarthikeyan** [comment]
Thanks Soulgalore. 
I configured sitespeed as batch command in Jenkins build configuration and worked fine. 

Win Batch Command:
sitespeed.io.cmd -u https://sitespeed.io –resultBaseDir ${WORKSPACE}/${BUILD_NUMBER} –junit >junit.xml

When I publish Junit test result in Jenkins post build , Build shows as unstable with the following msg : 
D:\******\JENKINS_HOME\workspace\sitespeedtest>sitespeed.io.cmd -u https://sitespeed.io –resultBaseDir ${WORKSPACE}/${BUILD_NUMBER} –junit  1>junit.xml 
Recording test results
**Build step 'Publish JUnit test result report' changed build result to UNSTABLE** 

Do you know how to resolve the above issue . Can you please add a sample screenshot of how the sitespeed test result will show/appear in Jenkins.Add screenshot into sitespeed documentation as well will be great full.
