### ISSUE TITLE
sitespeed-result is not a directory error on running the job that is configured for sitespeed.io

### ISSUE THREAD

**Issue by avellayappan** [sitespeedio/jenkins.sitespeed.io#6]
Here is the CI config:
Home dir: /Users/avellayappan/.jenkins/sitespeed.io-2.3.1/ 
(validated setup as ok)
Sitespeed.io configuration: -u http://www.ebay.com

Here is the call stack in the CI console output:
Started by user anonymous
Building in workspace C:\Users\avellayappan.jenkins\jobs\sitespeed.io\workspace
java.io.IOException: Cannot run program "bin/sitespeed.io" (in directory "\Users\avellayappan.jenkins\sitespeed.io-2.3.1"): CreateProcess error=2, The system cannot find the file specified
FATAL: C:\Users\avellayappan.jenkins\jobs\sitespeed.io\workspace\11\sitespeed-result is not a directory
java.lang.IllegalArgumentException: C:\Users\avellayappan.jenkins\jobs\sitespeed.io\workspace\11\sitespeed-result is not a directory
    at io.sitespeed.jenkins.util.FileUtil.getLastModifiedFileNameInDir(FileUtil.java:77)
    at io.sitespeed.jenkins.SitespeedBuilder.perform(SitespeedBuilder.java:173)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:566)
    at hudson.model.Run.execute(Run.java:1678)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:231)

Any inputs on this error message?

Thanks!

**Comment by BKarthikeyan** [comment]
Hi soulgalore , I am getting same issue as already posted above, Just want to know did the issue got fixed and how to resolve the issue.
 Build step failed with exception
java.lang.IllegalArgumentException: D:\******\Downloads\JENKINS_HOME\workspace\sitespeedtest\7\sitespeed-result is not a directory
	at io.sitespeed.jenkins.util.FileUtil.getLastModifiedFileNameInDir(FileUtil.java:77)
	at io.sitespeed.jenkins.SitespeedBuilder.perform(SitespeedBuilder.java:244)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
